"""Raw read-only API response schemas for the production backend."""

from app.schemas.availability import (
    DataAvailabilityResponse,
    DataSectionAvailabilityResponse,
)
from app.schemas.common import (
    MessageResponse,
    MissingSectionResponse,
    PaginationParams,
    RawDictResponse,
    RawResponseModel,
    SourceRef,
)
from app.schemas.engine import (
    AssembledRecommendationResponse,
    CandidateConfidenceResultResponse,
    CandidateFilterBundleResponse,
    CandidateFilterResultResponse,
    CandidatePlantMatchesResponse,
    ConfidenceFactorResponse,
    ConfidenceScoringBundleResponse,
    InputContextResponse,
    McdaMatrixBundleResponse,
    McdaMatrixRowResponse,
    McdaWeightsBundleResponse,
    NormalizedMcdaCriterionResponse,
    NormalizedMcdaMatrixBundleResponse,
    NormalizedMcdaMatrixRowResponse,
    ParameterGapResultResponse,
    PlantMatchResponse,
    PlantMatchingBundleResponse,
    PollutantGapBundleResponse,
    RecommendationAssemblyBundleResponse,
    RecommendationEvidenceSummaryResponse,
    ScientificWorkflowResultResponse,
    TreatmentNeedBundleResponse,
    TreatmentNeedResultResponse,
    TopsisCriterionContributionResponse,
    TopsisRankedCandidateResponse,
    TopsisRankingBundleResponse,
    WaterInputBundleResponse,
)
from app.schemas.nbs import (
    NbsCriteriaResponse,
    NbsFootprintResponse,
    NbsFullProfileResponse,
    NbsImplementationResponse,
    NbsOptionResponse,
    RemovalEfficiencyResponse,
)
from app.schemas.plant import PlantCatalogResponse, PlantMappingResponse, PlantResponse
from app.schemas.pollution import PollutionContextResponse, PollutionSourceResponse
from app.schemas.reference import (
    BasinResponse,
    ReferenceDataResponse,
    RegionResponse,
    SourceResponse,
    UseCaseResponse,
    WaterStationResponse,
)
from app.schemas.recommendation import (
    CitationResponse,
    RecommendationRequest,
    RecommendationResponse,
)
from app.schemas.river import (
    RiverContextResponse,
    RiverSegmentResponse,
    SiteStreamContextResponse,
)
from app.schemas.site import (
    SiteAttributesResponse,
    SiteProfileResponse,
    SiteStreamAttributesResponse,
)
from app.schemas.standards import (
    StandardResponse,
    StandardsListResponse,
    StandardsUseCaseResponse,
)
from app.schemas.water import (
    WaterDataResponse,
    WaterObservationResponse,
    WaterParameterSummaryResponse,
)

__all__ = [
    "BasinResponse",
    "AssembledRecommendationResponse",
    "CandidateConfidenceResultResponse",
    "CandidateFilterBundleResponse",
    "CandidateFilterResultResponse",
    "CandidatePlantMatchesResponse",
    "ConfidenceFactorResponse",
    "ConfidenceScoringBundleResponse",
    "DataAvailabilityResponse",
    "DataSectionAvailabilityResponse",
    "InputContextResponse",
    "MessageResponse",
    "McdaMatrixBundleResponse",
    "McdaMatrixRowResponse",
    "McdaWeightsBundleResponse",
    "MissingSectionResponse",
    "NbsCriteriaResponse",
    "NbsFootprintResponse",
    "NbsFullProfileResponse",
    "NbsImplementationResponse",
    "NbsOptionResponse",
    "NormalizedMcdaCriterionResponse",
    "NormalizedMcdaMatrixBundleResponse",
    "NormalizedMcdaMatrixRowResponse",
    "PaginationParams",
    "ParameterGapResultResponse",
    "PlantCatalogResponse",
    "PlantMatchResponse",
    "PlantMatchingBundleResponse",
    "PlantMappingResponse",
    "PlantResponse",
    "PollutionContextResponse",
    "PollutionSourceResponse",
    "PollutantGapBundleResponse",
    "RecommendationAssemblyBundleResponse",
    "RecommendationEvidenceSummaryResponse",
    "CitationResponse",
    "RecommendationRequest",
    "RecommendationResponse",
    "RawDictResponse",
    "RawResponseModel",
    "ReferenceDataResponse",
    "RegionResponse",
    "RemovalEfficiencyResponse",
    "RiverContextResponse",
    "RiverSegmentResponse",
    "ScientificWorkflowResultResponse",
    "SiteAttributesResponse",
    "SiteProfileResponse",
    "SiteStreamAttributesResponse",
    "SiteStreamContextResponse",
    "SourceRef",
    "SourceResponse",
    "StandardResponse",
    "StandardsListResponse",
    "StandardsUseCaseResponse",
    "TreatmentNeedBundleResponse",
    "TreatmentNeedResultResponse",
    "TopsisCriterionContributionResponse",
    "TopsisRankedCandidateResponse",
    "TopsisRankingBundleResponse",
    "UseCaseResponse",
    "WaterDataResponse",
    "WaterInputBundleResponse",
    "WaterObservationResponse",
    "WaterParameterSummaryResponse",
    "WaterStationResponse",
]
